import {readFile,writeFile,mkdir,copyFile,access,rm} from 'node:fs/promises';
import {join,dirname} from 'node:path';
import {lookup} from 'node:dns/promises';
import {existsSync} from 'node:fs';
import {embedEntity,bestImage,run} from './core.mjs';
export async function publicUrl(value){
 const u=new URL(value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('Use a public HTTP(S) media URL.');
 const addresses=await lookup(u.hostname,{all:true});
 if(!addresses.length||addresses.some(({address:a})=>/^(127\.|10\.|192\.168\.|169\.254\.|0\.|172\.(1[6-9]|2\d|3[01])\.|::|fc|fd|fe80|::ffff:)/i.test(a)))throw Error('Local network URLs are not supported.');return u.href;
}
async function fetchImage(url){
 for(let n=0;n<5;n++){
  await publicUrl(url);const r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(25000)});
  if(r.status>=300&&r.status<400){url=new URL(r.headers.get('location'),url).href;continue;}
  if(!r.ok)throw Error(`Artwork provider returned HTTP ${r.status}`);
  if(!r.headers.get('content-type')?.startsWith('image/'))throw Error('Artwork URL must return an image.');
  const chunks=[];let size=0;for await(const chunk of r.body){size+=chunk.length;if(size>10000000)throw Error('Artwork exceeds 10 MB.');chunks.push(chunk);}return Buffer.concat(chunks);
 }throw Error('Too many artwork redirects.');
}
const artCache=new Map();
async function imageToJpeg(url,target){
 const cached=artCache.get(url);if(cached&&existsSync(cached)){await copyFile(cached,target);return;}
 const input=target+'.source';await writeFile(input,await fetchImage(url));
 try{await run('ffmpeg',['-v','error','-y','-i',input,'-frames:v','1','-vf',"scale='min(1200,iw)':-2",'-q:v','2',target]);artCache.set(url,target);}finally{await rm(input,{force:true});}
}
export async function enrichSpotify(track){
 const id=track.spotify?.match(/\/track\/([a-zA-Z0-9]{22})/)?.[1]||track.id?.match(/^spotify:track:([a-zA-Z0-9]{22})$/)?.[1];
 if(!id||track.cover)return;
 try{
  const r=await fetch(`https://open.spotify.com/embed/track/${id}`,{signal:AbortSignal.timeout(20000)});if(!r.ok)return;
  const entity=embedEntity(await r.text());track.cover=bestImage(entity);track.date ||=entity.releaseDate?.isoString?.slice(0,10)||'';track.spotify ||= `https://open.spotify.com/track/${id}`;
 }catch{ /* Source thumbnail remains a fallback when Spotify is unavailable. */ }
}
export async function finishAudio(job,{folder,root,python}){
 const base=join(folder,job.filename),file=base+'.'+job.format;
 await access(file);await enrichSpotify(job.track);
 let info={};try{info=JSON.parse(await readFile(base+'.info.json','utf8'));}catch{}
 const t=job.track;
 let existingTags={};try{existingTags=JSON.parse(await run('ffprobe',['-v','error','-show_entries','format_tags','-of','json',file])).format?.tags||{};}catch{}
 const generated=String(info.description||existingTags.description||existingTags.synopsis||'');
 const blocks=generated.split(/\r?\n\r?\n/);
 const autoAlbum=/Provided to YouTube by/.test(blocks[0]||'')&&/Auto-generated by YouTube/.test(generated)?blocks[2]?.trim():'';

 if(t.origin==='youtube'){
  t.title=info.track||t.title;t.artist=(info.artists?.length?[...new Set(info.artists)].join(', '):info.artist)||t.artist||info.uploader?.replace(/ - Topic$/,'')||'';
 }
 t.album ||=info.album||existingTags.album||autoAlbum||'';t.albumArtist ||=info.album_artist||existingTags.album_artist||(t.album?t.artist:'');t.date ||=info.release_date||String(info.release_year||'')||existingTags.date||'';t.genre ||=info.genre||'';
 if(!t.duration)t.duration=info.duration||0;
 if(/^\d{8}$/.test(t.date))t.date=t.date.slice(0,4)+'-'+t.date.slice(4,6)+'-'+t.date.slice(6);
 const cover=base+'.cover.jpg';let found=false;const errors=[];
 if(job.artwork&&existsSync(join(folder,job.artwork))&&(!t.cover||t.cover===job.embeddedCoverUrl)){await copyFile(join(folder,job.artwork),cover);found=true;}
 if(!found&&t.cover){try{await imageToJpeg(t.cover,cover);found=true;job.artworkSource='original';}catch(e){errors.push(e.message);}}
 if(!found){
  for(const ext of ['jpg','jpeg','png','webp']){
   const thumb=base+'.'+ext;if(!existsSync(thumb))continue;
   try{await run('ffmpeg',['-v','error','-y','-i',thumb,'-frames:v','1','-vf',"scale='min(1200,iw)':-2",'-q:v','2',cover]);found=true;job.artworkSource='source thumbnail';break;}catch(e){errors.push(e.message);}
  }
 }
 if(!found&&bestImage(info)){try{await imageToJpeg(bestImage(info),cover);found=true;job.artworkSource='source thumbnail';}catch(e){errors.push(e.message);}}
 if(!found&&job.collection?.cover){try{await imageToJpeg(job.collection.cover,cover);found=true;job.artworkSource='collection cover';}catch(e){errors.push(e.message);}}
 if(!found)throw Error('No usable cover art. Add a cover image URL in track details and retry. '+errors.join(' '));
 const metadata={...t,collection:job.collection?.name||'',totalTracks:job.totalTracks||0,totalDiscs:job.totalDiscs||1};
 const tags=base+'.tags.json';await writeFile(tags,JSON.stringify(metadata));
 try{await run(python,[join(root,'scripts/tag_audio.py'),file,cover,tags]);}finally{await rm(tags,{force:true});}
 const artwork=`Artwork/${job.filename.replaceAll('/',' - ')}.jpg`;await mkdir(join(folder,'Artwork'),{recursive:true});await copyFile(cover,join(folder,artwork));job.artwork=artwork;
 if(!existsSync(join(folder,'cover.jpg'))){
  let collectionCover=false;
  if(job.collection?.cover){try{await imageToJpeg(job.collection.cover,join(folder,'cover.jpg'));collectionCover=true;}catch{}}
  if(!collectionCover)await copyFile(cover,join(folder,'cover.jpg'));
 }
 job.coverEmbedded=true;job.embeddedCoverUrl=t.cover;
 await rm(cover,{force:true});
 for(const ext of ['info.json','jpg','jpeg','png','webp'])await rm(base+'.'+ext,{force:true});
}
